monarch-initiative/ontogpt

- src/ontogpt/cli.py
If `output_format == "yaml"` , the line `output = codecs.getwriter("utf-8")(output)` prevents `output.write(dump_minimal_yaml(results))` to dump the results giving the error: `TypeError: write() argument must be str, not bytes` .
This patch fixes that issue.
> If output is YAML, codecs not needed

- src/ontogpt/templates/phenotype.py
- src/ontogpt/templates/phenotype.yaml
@cmungall this may be naive, but I wanted to try ontogpt and go through the motions. 
It is entirely possible that I am not yet understanding all of the thoughts here. I created this trivial phenotype model based on EQ, and I was hoping I could read a definition or label of a term and read it into the structure. I will need your handholding on this :P 
```
ontogpt extract -t phenotype.Trait "increased blood glucose levels"
input_text: increased blood glucose levels
raw_completion_output: "quality: increased blood glucose levels\nanatomical_entity:\
\ \nchemical_entity:"
prompt: 'Split the following piece of text into fields in the following format:
quality: <the phenotypic quality exibited by the phenotype>
anatomical_entity: <the name of the disease that is treated.>
chemical_entity: …
```
> Playing around: adding a  phenotype extractor

- pyproject.toml
@cmungall Improve the dependencies definition by moving some development dependencies to the devDependencies (e.g. tox), and created a new `web` optional dependency bundle to install all dependencies required to run the web service
Mentioned here: https://github.com/monarch-initiative/ontogpt/issues/3
> Improve dependencies, add a web optional

- Makefile
Fix #59.
The citation.cff doesn't get updated now, but it will still return the current version.
> Change citation updater in Makefile to get_version

- Makefile
- README.md
- project.Makefile
This should support easier use of custom templates - just drop them in the templates directory and make all.
Holding off on any dynamic compilation for now.
This may not work on mac OS make - not certain the explicit `wildcard` function is there.
> Makefile uses all templates

- .github/workflows/deploy-docs.yml
`gen-doc` is part of linkml and installed by poetry, so it needs to be called with `poetry run`.
> Fix for doc generation

- src/ontogpt/cli.py
This merge request fixes a bug where the annotators were not being skipped even when the 'skip_annotators' option was specified. Specifically, I have corrected the assignment of the skip_annotators option so that its value is now assigned to 'ke.skip_annotators' as intended, instead of being assigned to 'ke.client.skip_annotators'.
> Fixed a bug where the 'skip_annotators' option was being ignored

- src/ontogpt/cli.py
- src/ontogpt/clients/pubmed_client.py
@AgranyaGitHub @caufieldjh @pnrobinson along the lines of what we discussed today
> Add a command 'pubmed-annotate' to retrieve PMIDs for a search term, then apply a template to all of them to extract info

- src/ontogpt/cli.py
- src/ontogpt/io/rdf_exporter.py
- src/ontogpt/templates/ibd_literature.yaml
Writing to ttl or owl fails when the `RDFExporter` or `OWLExporter` are passed an `ExtractionResult.extracted_object` of None.
This checks for that condition first.
> Fixes for #139

- src/ontogpt/cli.py
- src/ontogpt/clients/openai_client.py
- src/ontogpt/engines/gpt4all_engine.py
- src/ontogpt/engines/spires_engine.py
- src/ontogpt/templates/composite_disease.py
Extraction-based commands can be passed the `--show_prompts` flag.
If used with `-vvv`, *all* prompts will be output to the logger in their full form.
Without that verbose flag, no additional output will be provided.
> Add option to show prompt

- src/ontogpt/__init__.py
- src/ontogpt/cli.py
- src/ontogpt/models.yaml
Fixes for:
* #191 
* Case when provided model name wasn't matching any known model - this should revert to the default model but was raising an error.
* A duplicate model name in the `models.yaml` - didn't cause error but may cause confusion.
> Repairs for incorrect model specification

- src/ontogpt/clients/openai_client.py
- src/ontogpt/engines/gpt4all_engine.py
- src/ontogpt/engines/spires_engine.py
Fixes #197
General guidelines:
- name arguments to calls unless order is absolutely predictable
- when adding new arguments to an existing function call, these go at the end by default
> Fixed bug where named arguments did not match up in recurse function.

- src/ontogpt/cli.py
There was a bug involving unnecessary encoding of the output string, but also an identical line getting repeated several times.
> Tidy up the CLI's `write_extraction` function

- src/ontogpt/cli.py
- src/ontogpt/engines/spires_engine.py
- src/ontogpt/evaluation/hpoa/eval_hpoa.py
- src/ontogpt/io/yaml_wrapper.py
Ensure YAML output contains separators so multiple documents may be loaded.
These need to go on outputs even if they're only a single doc (note that ruamel.yaml has a method called dump_all, but this only includes separators for multiple doc outputs).
> Fix for #215

- src/ontogpt/evaluation/ctd/eval_ctd.py
This is specific to the CTD eval for now, but hoping to avoid the same issue in other evals.
Fix #235.
Also include only unique predicted triples in output - many of these were fully redundant in the final object, though the extras were not included in score calculations since those are based on sets.
> Reduce redundancy in named entity list in evals

- src/ontogpt/templates/human_phenotype.py
- src/ontogpt/templates/human_phenotype.yaml
This includes some extra prompt text to encourage the model to return a list compatible with parsing, as one input text can have numerous entities to extract and GPT-3+ appears to be more likely to separate lists with commas than semicolons as lists grow longer.
This suggests that most text should be parsed this way, or at least some additional validation step can re-parse outputs if they look like "entity1, entity2, entity3" and don't ground
> Add a template specifically for extracting human phenotypes

- src/ontogpt/cli.py
- src/ontogpt/evaluation/ctd/eval_ctd.py
- src/ontogpt/evaluation/evaluation_engine.py
The evaluation engine now accepts a model name through the `eval` command.
> Add `model` parameter to evaluation engine

- poetry.lock
- src/ontogpt/evaluation/ctd/eval_ctd.py
- src/ontogpt/evaluation/ctd/eval_ctd_ner.py
- src/ontogpt/evaluation/resolver.py
- src/ontogpt/templates/core.py
- src/ontogpt/templates/core.yaml
- src/ontogpt/templates/ctd_ner.py
- src/ontogpt/templates/ctd_ner.yaml
Essentially the original DNER task plus chemical NER.
Based off the current CDR eval for consistency, though this means there is still a lot of redundancy between evals.
> Add NER eval for BC5CDR

- src/ontogpt/models.yaml
Add name of the preview version of gpt-4-turbo to the models config.
This will likely be replaced soon.
> Add `gpt-4-1106-preview`

- README.md
fix #256
@cmungall the CurateGPT OBO Academy video was public on YouTube; I assume it's also ok to share the link to the slides?
> Added links to a tutorial and a presentation about OntoGPT and CurateGPT

- Makefile
- src/ontogpt/templates/figure.py
- src/ontogpt/templates/figure.yaml
Currently seeing error:
```
jim (figures)$ poetry run ontogpt extract -t figure.FigureCaption -i caption.txt -o caption.yaml
Configuration file exists at /Users/jim/Library/Preferences/pypoetry, reusing this directory.
Consider moving TOML configuration files to /Users/jim/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
ERROR:root:HuggingFace Hub API key not found. See README.
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/jim/Library/Caches/pypoetry/virtualenvs/ontogpt-T28sWqJT-py3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/jim/Library/Caches/pypoetry/virtualenvs/ontogpt-T28sWqJT-py3.11 …
```
> Testing figures template.

- docs/functions.md
- src/ontogpt/cli.py
This enables passing a path to a directory through the `-i` input command for the `extract` command.
All files with the `.txt` suffix will be parsed as inputs and outputs will be written to the same output file.
> Enable running extractions on all files in a directory

- src/ontogpt/templates/data_sheets_schema.py
- src/ontogpt/templates/data_sheets_schema.yaml
This corresponds to https://github.com/bridge2ai/data-sheets-schema/blob/main/src/data_sheets_schema/schema/data_sheets_schema.yaml , but with adjustments to make it work (more) properly as an extraction schema.
It is intended for extraction of metadata for datasets and may be used with data repository pages (e.g., Zenodo, Dryad, etc), Github repo READMEs, documentation, manuscripts, and any other text describing a dataset.
Example usage: `ontogpt -vvv web-extract -t data_sheets_schema.Dataset -m gpt-4-1106-preview https://zenodo.org/records/10524821`
> Add data_sheets_schema template

- src/ontogpt/io/csv_wrapper.py
Fixes #353 -- not sure how universal this fix is, so would appreciate feedback!
In particular, it seemed like the previous implementation assumed that the relation dictionaries would have the keys `"subject", "predicate", "object"`, which at least in the case of the schema I've been working with, isn't the case; the relation dictionary keys are entity types, and there's no entry for the predicate.
For the moment, I just used the `rel_type` as the predicate in addition to the category; previously I had converted the lowercase&pluralized `rel_type` to the camelcase&singular relation type from the schema with a function that didn't use SchemaView; I assume using SchemaView is what I should do here, but for some reason, my SchemaView seems to be empty, even though my schema is properly …
> Debug relation formatting in csv_wrapper

- src/ontogpt/io/template_loader.py
Template schemas may now be passed to the `--template` option; pass the path to the YAML file. The schema may still include imports, like the `ontogpt` `core` schema, as long as they are present in the `templates` directory already (or are part of the standard `ontogpt` installation).
> Add custom template loader

- src/ontogpt/utils/multilingual.py
Multilanguage analysis now continues as expected if it encounters an error in prompt completion or grounding.
The output file will contain the text of the error.
All errors and prompt filenames are also written to a file named `errors.txt` in the output directory (e.g., for `malco` it's going to be in `/outputdir/raw_results/en/differentials_by_file/errors.txt`).
> Fix issue with early termination of multilanguage analysis runs

- docs/functions.md
- src/ontogpt/cli.py
This is useful when processing multiple documents and/or full texts, as they can get quite large.
> Add option to truncate input_text in outputs

- src/ontogpt/cli.py
- src/ontogpt/io/csv_exporter.py
Added an option to export "csv" - updated cli.py & wrote io/csv_exporter.py.
> Added CSV exporter

- docs/functions.md
- docs/setup.md
- poetry.lock
- pyproject.toml
- src/ontogpt/cli.py
The option for extracting from PDF with the `extract` command is now `--use-pdf`.
> Replace `textract` with `pymupdf`

- Makefile
- poetry.lock
- src/ontogpt/engines/knowledge_engine.py
- src/ontogpt/templates/drug_to_disease.py
- src/ontogpt/templates/drug_to_disease.yaml
Also add a new template and fix an issue with the Makefile targets for `gen-pydantic` (it doesn't accept the pydantic version argument anymore).
> Add caching for mapper

- docs/functions.md
- src/ontogpt/cli.py
- src/ontogpt/clients/llm_client.py
- src/ontogpt/engines/knowledge_engine.py
- src/ontogpt/prompts/qa/__init__.py
- tests/unit/test_clients/test_pubmed_client_unit.py
The `system-message` command allows a system-level message to be passed to the LLM.
For example, with an input file containing "How are you today":
```
$ ontogpt complete -m llama-3 -i temp/greeting.txt
I'm just a language model, I don't have emotions or feelings like humans do, so I don't have good or bad days. I'm always here and ready to chat with you, 24/7! How can I assist you today?
$ ontogpt complete -m llama-3 -i temp/greeting.txt--system-message "You are very grumpy today"
*grumble grumble* I'm terrible, thanks for asking. Everything is just so... annoying. The sun is shining too brightly, the birds are singing too loudly, and the air is filled with the scent of... *sigh*... everything. Just, ugh. Can't anyone just leave me alone for once? What's it to you, anyway? *mutter …
```
> Add system-message command

- docs/custom.md
- poetry.lock
- src/ontogpt/cli.py
- src/ontogpt/clients/pubmed_client.py
- src/ontogpt/engines/knowledge_engine.py
- src/ontogpt/engines/spires_engine.py
- src/ontogpt/evaluation/ctd/eval_ctd.py
- src/ontogpt/evaluation/ctd/eval_ctd_ner.py
- src/ontogpt/evaluation/maxo/eval_maxo.py
- tests/integration/test_knowledge_engines/test_spires_engine.py
Input text for extractions can be chunked by character (or by sentence, though this was already possible) to fit a token limit by using the `--max-text-length` option.
Otherwise, the full text is used.
> Expand option to set token/context limit

- src/ontogpt/io/template_loader.py
Removing `pydantic_version=2` keyword in initialization of `PydanticGenerator` object. It appears that this is an unsupported keyword argument with linkml 1.8.3 and was causing crashes in `ontogpt extract` calls. I did not test with linkml 1.8.0. Is `pydantic_version` necessary here?
> Removed `pydantic_version` keyword in template_loader.py

- src/ontogpt/engines/spires_engine.py
- src/ontogpt/templates/core.py
- src/ontogpt/templates/core.yaml
- src/ontogpt/utils/parse_utils.py
Where possible (i.e., an extracted named entity is explicitly mentioned in the input text), its corresponding span will be provided in the list of named entities, a la:
```yaml
named_entities:
- id: AUTO:erosion
label: erosion
original_spans:
- 29:35
- id: SNOMEDCT:263913002
label: ulceration
original_spans:
- 44:53
```
These will *not* be included if the named entity isn't present in the input text, and this may happen if the prompt instructs the raw response to be transformed in some way (e.g., the raw text contains "ulceration" but the extraction instructions cause the LLM to represent it as "TRUE", as in "yes there is an ulceration", then the span details won't appear)
> Provide spans of named entities

- src/ontogpt/cli.py
This mirrors the behavior of the same option in the `extract` command.
Fixes #468.
> Add --target-class option to web_extract command

- src/ontogpt/clients/llm_client.py
As described in #487, currently an openai key is loaded even if the requested model starts with ollama. This PR fixes the issue for me.
> Fix openapi key required for loading ollama models

- poetry.lock
- src/ontogpt/cli.py
The following CLI commands were producing TypeErrors depending on the inputs used:
* extract
* complete
* clinical_notes
These are fixes.
> Fix errors in CLI

- poetry.lock
- src/ontogpt/io/template_loader.py
- src/ontogpt/templates/predator_prey.py
- src/ontogpt/templates/predator_prey.yaml
Some templates don't have root classes specified.
With this PR, the default behavior will be to select the first class from a template (not including the core classes) if a root is not specified in the schema or with the `--target-class` parameter.
> Improve handling of missing root class definition

- src/ontogpt/templates/mic.py
- src/ontogpt/templates/mic.yaml
The main change here is to combine the relationship classes for nutrient + disease and nutrient + phenotype into a single relationship type, now in the slot `nutrient_to_feature_relationships`. 
Also various prompt engineering tweaks throughout, including some explicit suggestions of appropriate Biolink predicates.
> Updates for the MIC extraction template

- src/ontogpt/templates/drug.py
- src/ontogpt/templates/drug.yaml
Updates to the `drug` extraction template to allow for extraction of multiple sets of drug mechanisms, along with a variety of other improvements to descriptions, annotators, and prefixes.
> Update drug template
