- .github/workflows/qc.yml
Added `tox -e lint` in the workflow
> Add linter to workflow

- tests/input/recipe-urls.csv
> Add recipe URL

- src/ontogpt/cli.py
- src/ontogpt/engines/enrichment.py
- src/ontogpt/engines/knowledge_engine.py
- src/ontogpt/engines/resolver.py
- tests/integration/test_knowledge_engines/test_enrichment.py
command:
`ontogpt enrichment HGNC:8858 HGNC:8859 HGNC:9719`
Results:
_Term enrichment test:_
_Commonality: Protein targeting to the Peroxisome. All the genes are involved in targeting proteins to the peroxisome membrane, matrix or both, and they are all located in cytoplasm; peroxisome; and/or endoplasmic reticulum. Additionally, they all enable different types of binding activity and/or hydrolysing activity which likely contribute to their roles in protein import_
this uses the Alliance API to fetch gene descriptions then summarize over them
> Adding gene set enrichment

- README.md
- src/ontogpt/cli.py
> Add option to provide path to input file

- src/ontogpt/evaluation/enrichment/eval_enrichment.py
> Missed parenthesis for random.SystemRamdom()

- src/ontogpt/cli.py
> Raise FileNotFoundError if filepath for extract is missing

- src/ontogpt/cli.py
- src/ontogpt/clients/openai_client.py
per discussion with @cmungall @caufieldjh @pnrobinson
> Added command to generate mock clinical notes

- README.md
- poetry.lock
- pyproject.toml
- src/ontogpt/streamlit/spindoctor.py
after entering list making selections and submitting:
> Added streamlit app for spindoctor

- README.md
noticed this while reading the readme
> very small typo fix

- src/ontogpt/templates/environmental_metadata.py
- src/ontogpt/templates/environmental_metadata.yaml
- tests/input/cases/environmental-metadata-1.txt
- tests/input/cases/environmental-metadata-2.txt
- tests/input/cases/environmental-metadata-3.txt
For trial of EDI data classification.
> Init environmental metadata template

- src/ontogpt/clients/pubmed_client.py
> A fix for encountering missing PubmedData fields

- src/ontogpt/cli.py
> Name params in call to complete

- docs/evaluations.md
- docs/functions.md
- src/ontogpt/cli.py
- src/ontogpt/evaluation/ctd/eval_ctd.py
- src/ontogpt/evaluation/evaluation_engine.py
This looks like 
```bash
ontogpt -vvv eval EvalCTD --num-tests 1 --chunking
```
It is False by default.
> Add parameter to disable chunking in SPIRES evals

- src/ontogpt/templates/datasheet.py
- src/ontogpt/templates/datasheet.yaml
See https://github.com/bridge2ai/data-sheets-schema
> Create draft template for extracting metadata to Datasheets

- src/ontogpt/templates/nmdc_schema_data.py
- src/ontogpt/templates/nmdc_schema_data.yaml
This is the nmdc-schema: https://github.com/microbiomedata/nmdc-schema
Study/sample metadata should ideally be represented by ENVO terms, but this is not always the case.
This PR introduces a template for extracting nmdc-schema compatible contents from study/sample data entries.
> Try extraction to nmdc-schema

- src/ontogpt/cli.py
> Add list-templates command

- src/ontogpt/cli.py
- src/ontogpt/engines/knowledge_engine.py
- src/ontogpt/engines/pheno_engine.py
- src/ontogpt/io/csv_wrapper.py
Issues with the synonym and diagnose functions had a related cause.
This PR also includes more error handling for both functions.
> Repair synonym and diagnose functions

- src/ontogpt/clients/openai_client.py
> Make azure_settings import conditional on using the azure_select flag

- src/ontogpt/engines/knowledge_engine.py
- src/ontogpt/io/html_exporter.py
- src/ontogpt/templates/biotic_interaction.yaml
- src/ontogpt/webapp/html/form.html
- src/ontogpt/webapp/main.py
Webapp now has better error handling and supports LLM selection.
> More fixes for the webapp

- poetry.lock
- pyproject.toml
> Bump version to 0.3.15

- poetry.lock
- src/ontogpt/cli.py
Encoding errors will be ignored when parsing text from files.
> Partial fix for #417

- src/ontogpt/templates/miro.py
- src/ontogpt/templates/miro.yaml
Initial evaluation results are here: https://github.com/monarch-initiative/ontogpt-experiments/tree/main/experiments/miro
> Add template for MIRO checklist extraction

- poetry.lock
- src/ontogpt/templates/food.py
- src/ontogpt/templates/food.yaml
This is very similar to `foodon_simple` but without any ontology language.
> Add new food extraction template

- poetry.lock
- pyproject.toml
- src/ontogpt/evaluation/drugmechdb/datamodel/drugmechdb.py
Also avoiding a persistent Pydantic warning
> Dependency updates and adaptations

- poetry.lock
- pyproject.toml
> Update dependency on python-multipart and fastapi

- poetry.lock
- pyproject.toml
- src/ontogpt/engines/spires_engine.py
- src/ontogpt/templates/adverse_outcome_pathway.py
- src/ontogpt/templates/adverse_outcome_pathway.yaml
- tests/unit/test_unit_cli.py
Also some type fixes and a fix for the CLI tests.
> Add template for AOP extraction
